In [1]:
import tensorflow as tf
tf.__version__

'2.0.0-rc1'

### 构造模型

In [2]:
model = tf.keras.Sequential([tf.keras.layers.Dense(256,activation="relu"),
                            tf.keras.layers.Dense(10)])

In [3]:
x = tf.random.uniform(shape=(2,20))
y = model(x)

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                multiple                  5376      
_________________________________________________________________
dense_1 (Dense)              multiple                  2570      
Total params: 7,946
Trainable params: 7,946
Non-trainable params: 0
_________________________________________________________________


#### 访问模型

In [13]:
model.layers[0].weights

[<tf.Variable 'sequential/dense/kernel:0' shape=(20, 256) dtype=float32, numpy=
 array([[ 0.12338224, -0.05752262,  0.10639602, ..., -0.07265662,
          0.01551916, -0.13621736],
        [-0.0282371 ,  0.14639828,  0.06103985, ...,  0.09050238,
         -0.02041058, -0.04890908],
        [-0.01160067,  0.02590731, -0.03611272, ...,  0.05856945,
          0.04666948, -0.14225008],
        ...,
        [ 0.13189662, -0.00903012, -0.02712577, ...,  0.13598704,
          0.04605314,  0.0672358 ],
        [-0.08979176,  0.11992276, -0.07809924, ...,  0.02791728,
          0.14690307,  0.10296309],
        [-0.09978224,  0.1166257 ,  0.13766968, ..., -0.00552449,
          0.00480132,  0.02851371]], dtype=float32)>,
 <tf.Variable 'sequential/dense/bias:0' shape=(256,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [14]:
model.get_weights()

[array([[ 0.12338224, -0.05752262,  0.10639602, ..., -0.07265662,
          0.01551916, -0.13621736],
        [-0.0282371 ,  0.14639828,  0.06103985, ...,  0.09050238,
         -0.02041058, -0.04890908],
        [-0.01160067,  0.02590731, -0.03611272, ...,  0.05856945,
          0.04666948, -0.14225008],
        ...,
        [ 0.13189662, -0.00903012, -0.02712577, ...,  0.13598704,
          0.04605314,  0.0672358 ],
        [-0.08979176,  0.11992276, -0.07809924, ...,  0.02791728,
          0.14690307,  0.10296309],
        [-0.09978224,  0.1166257 ,  0.13766968, ..., -0.00552449,
          0.00480132,  0.02851371]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

#### 参数初始化

In [17]:
model2 = tf.keras.Sequential([tf.keras.layers.Dense(256,activation="relu",kernel_initializer=tf.keras.initializers.he_normal(),bias_initializer = tf.keras.initializers.zeros()),
                            tf.keras.layers.Dense(10,kernel_initializer = tf.keras.initializers.lecun_normal())])

In [18]:
model2(x)

<tf.Tensor: id=261, shape=(2, 10), dtype=float32, numpy=
array([[-0.867055  ,  0.9218145 , -0.39984056, -0.1287399 ,  0.43834788,
        -1.0307788 , -0.7092801 , -0.22422034, -0.29905924,  0.21123254],
       [-0.26173335,  0.7217271 , -0.24359123, -0.33488107,  0.20550153,
        -1.476892  ,  0.11222324, -0.7347325 ,  0.27864006,  0.5729934 ]],
      dtype=float32)>

#### 自定义初始化

In [20]:
def custon_init(shape,dtype):
    return tf.random.normal(shape,dtype=dtype)

In [24]:
model3 = tf.keras.layers.Dense(20,kernel_initializer=custon_init,bias_initializer=custon_init)

In [26]:
x = tf.random.normal(shape=(4,5))
model3(x)

<tf.Tensor: id=331, shape=(4, 20), dtype=float32, numpy=
array([[ 2.4996285e+00, -2.2661326e+00, -4.1436219e+00,  7.8802645e-01,
         1.9263575e+00,  9.3831408e-01, -2.0118103e+00,  1.6978300e+00,
         1.6855745e+00,  5.2597909e+00, -2.8485258e+00, -4.2393434e-01,
         1.5779448e+00, -2.3011146e+00,  1.4897611e+00,  2.7660012e+00,
        -4.3800492e+00,  7.5995171e-01, -4.9139175e+00,  1.8347940e+00],
       [-2.4028172e+00, -1.0048705e+00, -5.0989938e+00, -1.0276605e+00,
         1.0590660e+01,  2.8823504e+00,  2.6366097e-01, -2.8015046e+00,
         4.8363724e+00, -1.4197335e+00,  1.2619346e+00, -6.3780437e+00,
        -3.4786794e+00,  2.7386060e+00,  5.2082419e-01, -1.8333316e+00,
         1.9801116e-01, -3.3387222e+00, -6.0439110e-05, -3.3582041e+00],
       [ 2.7016888e+00, -9.2030829e-01, -4.6253935e-01,  1.8382086e+00,
        -7.9194498e-01, -2.9542106e-01, -1.5112060e+00,  3.5395298e+00,
         7.9595917e-01,  2.1228631e+00, -1.8427997e+00,  1.0792689e+00,
     

In [27]:
model3.weights

[<tf.Variable 'dense_7/kernel:0' shape=(5, 20) dtype=float32, numpy=
 array([[ 0.45920402, -0.5867202 ,  0.00330317,  1.4544914 , -1.2760887 ,
         -0.7474062 , -0.5675332 ,  1.6731852 ,  1.3729668 ,  0.65240663,
         -0.81190807,  1.0149175 , -0.5573179 , -0.2652778 , -1.9066402 ,
         -0.02936807,  2.1595957 ,  1.1616007 , -0.946991  ,  0.7445577 ],
        [-0.09839691, -0.13987663, -0.44504848, -0.62686515, -0.6384494 ,
          0.60696316,  0.07586614, -0.02301845,  0.03838044,  1.6386346 ,
         -1.6370806 ,  0.01161741,  0.74653643, -0.22556812,  1.6108478 ,
          0.6964037 , -2.3477144 , -0.33739766, -0.5958138 ,  0.5181274 ],
        [ 0.13808677,  1.0614382 ,  1.3485552 , -1.2653838 , -1.6361557 ,
         -0.5613568 , -1.052082  ,  0.75414085, -1.4885199 , -0.6346769 ,
          0.27198827,  1.5046318 , -0.61862576, -0.0143066 ,  0.33438998,
          0.5855123 ,  0.8316061 , -0.98011255, -0.28069264,  1.9791443 ],
        [-1.3604623 , -0.1627839 , -1.42

#### 参数共享
keras中参数共享实现方式是重复使用层

In [38]:
dense = tf.keras.layers.Dense(32)

model = tf.keras.Sequential([
    dense,
    tf.keras.layers.Dense(16),
    dense,
    tf.keras.layers.Dense(2)
])


In [39]:
left_x = tf.random.normal(shape=(4,3))

model(left_x)

<tf.Tensor: id=4176, shape=(4, 2), dtype=float32, numpy=
array([[ 0.16196586,  0.12407538],
       [-0.0735413 , -0.08775569],
       [-0.13205865, -0.54206514],
       [ 0.87240314,  1.6639346 ]], dtype=float32)>

In [40]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             multiple                  128       
_________________________________________________________________
dense_16 (Dense)             multiple                  528       
_________________________________________________________________
dense_17 (Dense)             multiple                  34        
Total params: 690
Trainable params: 690
Non-trainable params: 0
_________________________________________________________________
