In [1]:
import tensorflow as tf 
tf.__version__

'2.0.0-rc1'

## 创建tensor

In [2]:
a = tf.range(1,10)

In [3]:
a

<tf.Tensor: id=3, shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

### 查看shape

In [4]:
tf.shape(a)

<tf.Tensor: id=4, shape=(1,), dtype=int32, numpy=array([9])>

In [5]:
a.get_shape()

TensorShape([9])

### 变换shape

In [6]:
b = tf.reshape(a,[3,3])
b

<tf.Tensor: id=6, shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [7]:
a

<tf.Tensor: id=3, shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [8]:
tf.shape(b)

<tf.Tensor: id=7, shape=(2,), dtype=int32, numpy=array([3, 3])>

### 查看个数

In [9]:
tf.size(b)

<tf.Tensor: id=8, shape=(), dtype=int32, numpy=9>

In [10]:
tf.reduce_sum(a)

<tf.Tensor: id=10, shape=(), dtype=int32, numpy=45>

### 创建全零tensor

In [11]:
c = tf.zeros([3,2])

In [12]:
c

<tf.Tensor: id=13, shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [13]:
tf.zeros_like(b)

<tf.Tensor: id=14, shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

### 创建全一tensor

In [14]:
tf.ones([2,2])

<tf.Tensor: id=17, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [15]:
tf.ones_like(c)

<tf.Tensor: id=20, shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

### 通过numpy数值创建

In [16]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: id=21, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

### 随机初始化

In [17]:
# 生成均值为0方差为1的tensor
tf.random.normal([4,3],mean = 0,stddev=1)

<tf.Tensor: id=27, shape=(4, 3), dtype=float32, numpy=
array([[ 0.74652797,  0.18566968, -0.46807286],
       [-0.489874  , -0.0597236 ,  3.3507445 ],
       [ 0.76154804, -0.40215474,  2.11086   ],
       [ 0.2961196 ,  0.15220016,  0.7629575 ]], dtype=float32)>

### 随机初始化 正态分布裁切掉2个标准差

In [18]:
tf.random.truncated_normal([3,4])

<tf.Tensor: id=33, shape=(3, 4), dtype=float32, numpy=
array([[-0.215455  , -0.78976625, -0.02184092,  0.5592283 ],
       [-1.301123  , -1.2414213 ,  1.7587675 , -0.49630147],
       [-0.3465815 , -1.0008321 ,  0.8734915 , -0.972387  ]],
      dtype=float32)>

### 均匀分布

In [19]:
tf.random.uniform(shape=[3,4])

<tf.Tensor: id=40, shape=(3, 4), dtype=float32, numpy=
array([[0.847008  , 0.9868163 , 0.7804545 , 0.04288089],
       [0.4304285 , 0.9906976 , 0.14140499, 0.9446242 ],
       [0.07104564, 0.5628555 , 0.40328145, 0.5369803 ]], dtype=float32)>

## 运算

In [20]:
a = tf.random.normal([3,4])
a

<tf.Tensor: id=46, shape=(3, 4), dtype=float32, numpy=
array([[-2.108838  , -0.0063532 , -2.7925699 ,  0.86254686],
       [-0.2941902 , -1.5473562 ,  0.2930097 , -1.2153023 ],
       [ 0.79547495, -0.8895502 ,  0.3445812 ,  1.9056346 ]],
      dtype=float32)>

In [21]:
b = tf.ones([3,4])
b

<tf.Tensor: id=49, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [22]:
c = a+b
c

<tf.Tensor: id=50, shape=(3, 4), dtype=float32, numpy=
array([[-1.1088381 ,  0.9936468 , -1.7925699 ,  1.8625469 ],
       [ 0.70580983, -0.54735625,  1.2930098 , -0.21530235],
       [ 1.795475  ,  0.11044979,  1.3445811 ,  2.9056346 ]],
      dtype=float32)>

In [23]:
d = a*b
d

<tf.Tensor: id=51, shape=(3, 4), dtype=float32, numpy=
array([[-2.108838  , -0.0063532 , -2.7925699 ,  0.86254686],
       [-0.2941902 , -1.5473562 ,  0.2930097 , -1.2153023 ],
       [ 0.79547495, -0.8895502 ,  0.3445812 ,  1.9056346 ]],
      dtype=float32)>

In [24]:
a-b

<tf.Tensor: id=52, shape=(3, 4), dtype=float32, numpy=
array([[-3.108838  , -1.0063533 , -3.7925699 , -0.13745314],
       [-1.2941902 , -2.5473561 , -0.7069903 , -2.2153025 ],
       [-0.20452505, -1.8895502 , -0.6554188 ,  0.90563464]],
      dtype=float32)>

In [25]:
b = tf.random.uniform([4,3])

In [26]:
tf.matmul(a,b)

<tf.Tensor: id=60, shape=(3, 3), dtype=float32, numpy=
array([[-1.8255837 , -0.42006573, -2.7573693 ],
       [-0.35543337, -1.4038448 , -1.5874077 ],
       [ 0.11739725,  0.83086586,  0.8770962 ]], dtype=float32)>

In [27]:
tf.transpose(a)

<tf.Tensor: id=62, shape=(4, 3), dtype=float32, numpy=
array([[-2.108838  , -0.2941902 ,  0.79547495],
       [-0.0063532 , -1.5473562 , -0.8895502 ],
       [-2.7925699 ,  0.2930097 ,  0.3445812 ],
       [ 0.86254686, -1.2153023 ,  1.9056346 ]], dtype=float32)>

In [28]:
e = tf.random.uniform([3,3],minval = 10,maxval = 100)
e

<tf.Tensor: id=69, shape=(3, 3), dtype=float32, numpy=
array([[85.42008 , 61.71834 , 51.57955 ],
       [72.45433 , 78.63154 , 14.699884],
       [22.056915, 41.531364, 67.96298 ]], dtype=float32)>

In [29]:
tf.identity(e)

<tf.Tensor: id=69, shape=(3, 3), dtype=float32, numpy=
array([[85.42008 , 61.71834 , 51.57955 ],
       [72.45433 , 78.63154 , 14.699884],
       [22.056915, 41.531364, 67.96298 ]], dtype=float32)>

### 数组拼接

In [30]:
a = tf.range(1,10)
a = tf.reshape(a,[3,3])
a

<tf.Tensor: id=75, shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [31]:
b = tf.range(2,20,delta=2)
b = tf.reshape(b,[3,3])
b

<tf.Tensor: id=81, shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])>

In [32]:
c = tf.concat([a,b],axis=0)
c

<tf.Tensor: id=83, shape=(6, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])>

In [33]:
c = tf.concat([a,b],axis=1)
c

<tf.Tensor: id=85, shape=(3, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])>

In [34]:
c = tf.concat([a,b],axis=2)
c

InvalidArgumentError: ConcatOp : Expected concatenating dimensions in the range [-2, 2), but got 2 [Op:ConcatV2] name: concat

In [35]:
tf.stack([a,b],axis=0)

<tf.Tensor: id=87, shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])>

In [36]:
tf.stack([a,b],axis=1)

<tf.Tensor: id=88, shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  4,  6]],

       [[ 4,  5,  6],
        [ 8, 10, 12]],

       [[ 7,  8,  9],
        [14, 16, 18]]])>

In [37]:
tf.stack([a,b],axis=2)

<tf.Tensor: id=89, shape=(3, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])>

## 自动梯度

In [38]:
@tf.function
def fn(x1,x2):
    return 2*x1**2 + 3*x2 +10

In [39]:
y = fn(3,4)
y

<tf.Tensor: id=96, shape=(), dtype=int32, numpy=40>

In [40]:
x1 = tf.constant(5.0)
x2 =  tf.constant(6.0)

with tf.GradientTape() as tape:
    tape.watch(x1)
    tape.watch(x2)
    y = fn(x1,x2)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [41]:
gradients = []
dy_dx = tape.gradient(y,[x1,x2])

In [42]:
dy_dx

[<tf.Tensor: id=157, shape=(), dtype=float32, numpy=20.0>,
 <tf.Tensor: id=158, shape=(), dtype=float32, numpy=3.0>]