In [ ]:
import tensorflow as tf
tf.__version__

## 创建tensor

In [2]:
a = tf.range(1,10)

In [3]:
a

<tf.Tensor: id=3, shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

### 查看shape

In [4]:
tf.shape(a)

<tf.Tensor: id=4, shape=(1,), dtype=int32, numpy=array([9])>

In [5]:
a.get_shape()

TensorShape([9])

### 变换shape

In [6]:
b = tf.reshape(a,[3,3])
b

<tf.Tensor: id=6, shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [7]:
a

<tf.Tensor: id=3, shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [8]:
tf.shape(b)

<tf.Tensor: id=7, shape=(2,), dtype=int32, numpy=array([3, 3])>

### 查看个数

In [9]:
tf.size(b)

<tf.Tensor: id=8, shape=(), dtype=int32, numpy=9>

In [10]:
tf.reduce_sum(a)

<tf.Tensor: id=10, shape=(), dtype=int32, numpy=45>

### 创建全零tensor

In [11]:
c = tf.zeros([3,2])

In [12]:
c

<tf.Tensor: id=13, shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [13]:
tf.zeros_like(b)

<tf.Tensor: id=14, shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

### 创建全一tensor

In [14]:
tf.ones([2,2])

<tf.Tensor: id=17, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [15]:
tf.ones_like(c)

<tf.Tensor: id=20, shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

### 通过numpy数值创建

In [16]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: id=21, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

### 随机初始化

In [17]:
# 生成均值为0方差为1的tensor
tf.random.normal([4,3],mean = 0,stddev=1)

<tf.Tensor: id=27, shape=(4, 3), dtype=float32, numpy=
array([[ 0.29027987, -0.5696575 , -1.2426447 ],
       [ 1.0195128 , -1.4477636 , -1.8524324 ],
       [-0.98166364,  0.32680008, -0.62386495],
       [-1.4591895 ,  0.74578303,  1.765795  ]], dtype=float32)>

### 随机初始化 正态分布裁切掉2个标准差

In [18]:
tf.random.truncated_normal([3,4])

<tf.Tensor: id=33, shape=(3, 4), dtype=float32, numpy=
array([[-1.3671712 ,  0.15953329, -1.4575789 , -1.143924  ],
       [-0.4947853 , -1.2937084 , -1.9045621 ,  0.7449252 ],
       [ 0.04833466,  0.46037823, -0.06734485, -0.4633063 ]],
      dtype=float32)>

### 均匀分布

In [19]:
tf.random.uniform(shape=[3,4])

<tf.Tensor: id=40, shape=(3, 4), dtype=float32, numpy=
array([[0.57412493, 0.9740925 , 0.5816971 , 0.99086785],
       [0.39874935, 0.16968846, 0.54065895, 0.44685197],
       [0.4260602 , 0.7600963 , 0.73412645, 0.7010472 ]], dtype=float32)>

## 运算

In [20]:
a = tf.random.normal([3,4])
a

<tf.Tensor: id=46, shape=(3, 4), dtype=float32, numpy=
array([[-0.75625014,  1.0638567 ,  0.94465286,  0.02519507],
       [ 0.7846673 ,  0.19086279,  1.1770703 , -1.4053015 ],
       [-3.0607219 ,  0.09342171, -0.93188465, -0.7395967 ]],
      dtype=float32)>

In [21]:
b = tf.ones([3,4])
b

<tf.Tensor: id=49, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [22]:
c = a+b
c

<tf.Tensor: id=50, shape=(3, 4), dtype=float32, numpy=
array([[ 0.24374986,  2.0638566 ,  1.9446528 ,  1.0251951 ],
       [ 1.7846673 ,  1.1908628 ,  2.1770701 , -0.40530145],
       [-2.0607219 ,  1.0934217 ,  0.06811535,  0.26040328]],
      dtype=float32)>

In [23]:
d = a*b
d

<tf.Tensor: id=51, shape=(3, 4), dtype=float32, numpy=
array([[-0.75625014,  1.0638567 ,  0.94465286,  0.02519507],
       [ 0.7846673 ,  0.19086279,  1.1770703 , -1.4053015 ],
       [-3.0607219 ,  0.09342171, -0.93188465, -0.7395967 ]],
      dtype=float32)>

In [24]:
a-b

<tf.Tensor: id=52, shape=(3, 4), dtype=float32, numpy=
array([[-1.7562501 ,  0.06385672, -0.05534714, -0.97480494],
       [-0.21533269, -0.8091372 ,  0.17707026, -2.4053016 ],
       [-4.060722  , -0.9065783 , -1.9318846 , -1.7395967 ]],
      dtype=float32)>

In [25]:
b = tf.random.uniform([4,3])

In [26]:
tf.matmul(a,b)

<tf.Tensor: id=60, shape=(3, 3), dtype=float32, numpy=
array([[ 1.1440614 ,  1.0059583 ,  0.966174  ],
       [ 0.7656131 ,  0.8407941 , -0.36202434],
       [-1.3461576 , -2.5660787 , -1.0820291 ]], dtype=float32)>

In [27]:
tf.transpose(a)

<tf.Tensor: id=62, shape=(4, 3), dtype=float32, numpy=
array([[-0.75625014,  0.7846673 , -3.0607219 ],
       [ 1.0638567 ,  0.19086279,  0.09342171],
       [ 0.94465286,  1.1770703 , -0.93188465],
       [ 0.02519507, -1.4053015 , -0.7395967 ]], dtype=float32)>

In [28]:
e = tf.random.uniform([3,3],minval = 10,maxval = 100)
e

<tf.Tensor: id=69, shape=(3, 3), dtype=float32, numpy=
array([[77.032425, 32.174175, 38.21286 ],
       [79.83407 , 73.976425, 93.837616],
       [24.610937, 95.750755, 58.03199 ]], dtype=float32)>

In [29]:
tf.identity(e)

<tf.Tensor: id=70, shape=(3, 3), dtype=float32, numpy=
array([[77.032425, 32.174175, 38.21286 ],
       [79.83407 , 73.976425, 93.837616],
       [24.610937, 95.750755, 58.03199 ]], dtype=float32)>

### 数组拼接

In [30]:
a = tf.range(1,10)
a = tf.reshape(a,[3,3])
a

<tf.Tensor: id=76, shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [31]:
b = tf.range(2,20,delta=2)
b = tf.reshape(b,[3,3])
b

<tf.Tensor: id=82, shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])>

In [32]:
c = tf.concat([a,b],axis=0)
c

<tf.Tensor: id=84, shape=(6, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])>

In [33]:
c = tf.concat([a,b],axis=1)
c

<tf.Tensor: id=86, shape=(3, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])>

In [34]:
c = tf.concat([a,b],axis=2)
c

InvalidArgumentError: ConcatOp : Expected concatenating dimensions in the range [-2, 2), but got 2 [Op:ConcatV2] name: concat

In [35]:
tf.stack([a,b],axis=0)

<tf.Tensor: id=88, shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])>

In [36]:
tf.stack([a,b],axis=1)

<tf.Tensor: id=89, shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  4,  6]],

       [[ 4,  5,  6],
        [ 8, 10, 12]],

       [[ 7,  8,  9],
        [14, 16, 18]]])>

In [37]:
tf.stack([a,b],axis=2)

<tf.Tensor: id=90, shape=(3, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])>

## 自动梯度

In [38]:
@tf.function
def fn(x1,x2):
    return 2*x1**2 + 3*x2 +10

In [39]:
y = fn(3,4)
y

<tf.Tensor: id=97, shape=(), dtype=int32, numpy=40>

In [40]:
x1 = tf.constant(5.0)
x2 =  tf.constant(6.0)

with tf.GradientTape() as tape:
    tape.watch(x1)
    tape.watch(x2)
    y = fn(x1,x2)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [41]:
gradients = []
dy_dx = tape.gradient(y,[x1,x2])

In [42]:
dy_dx

[<tf.Tensor: id=158, shape=(), dtype=float32, numpy=20.0>,
 <tf.Tensor: id=159, shape=(), dtype=float32, numpy=3.0>]

In [ ]:
!pip install --upgrade tensorflow-gpu==2.0.0-rc1