In [1]:
import tensorflow as tf
tf.__version__

'2.0.0-rc2'

### 池化层
池化层的主要作用是减少数据对空间的敏感，主要有最大池化和平均池化

In [2]:
def max_pool(X,pool_size,mode="max"):
    c_i,h,w = X.shape
    p_h,p_w = pool_size
    out = []
    o_h,o_w = X.shape[1] - p_h + 1,X.shape[2] -p_w + 1
    for c in range(c_i):
        c_out = []
        for i in range(o_h):
            for j in range(o_w):
                x = X[c,i:i+p_h,j:j+p_w]
                c_out.append( (tf.reduce_max(x) if mode == "max" else tf.reduce_mean(x)) )
        out.append(tf.reshape(tf.stack(c_out),shape=(o_h,o_w)))
    return tf.stack(out)

In [3]:
x = tf.random.normal(shape=(1,5,5))
x

<tf.Tensor: id=5, shape=(1, 5, 5), dtype=float32, numpy=
array([[[-1.6190044 , -1.7472318 , -1.597117  ,  0.6069642 ,
          0.6292278 ],
        [-1.3054851 , -0.08884629, -0.02536662,  0.64657575,
         -1.3497806 ],
        [-0.64827347,  0.30910575,  1.5853575 , -1.8190321 ,
         -0.583722  ],
        [ 0.42387375,  1.5084459 ,  1.0241814 , -0.3987099 ,
         -0.479944  ],
        [ 1.0801529 , -0.28132275,  1.5214012 ,  0.79146785,
         -0.932343  ]]], dtype=float32)>

In [4]:
max_pool(x,(2,2))

<tf.Tensor: id=105, shape=(1, 4, 4), dtype=float32, numpy=
array([[[-0.08884629, -0.02536662,  0.64657575,  0.64657575],
        [ 0.30910575,  1.5853575 ,  1.5853575 ,  0.64657575],
        [ 1.5084459 ,  1.5853575 ,  1.5853575 , -0.3987099 ],
        [ 1.5084459 ,  1.5214012 ,  1.5214012 ,  0.79146785]]],
      dtype=float32)>

In [5]:
max_pool(x,(2,2),mode = "avg")

<tf.Tensor: id=205, shape=(1, 4, 4), dtype=float32, numpy=
array([[[-1.1901419 , -0.8646405 , -0.09223591,  0.1332468 ],
        [-0.4333748 ,  0.4450626 ,  0.09688365, -0.77648973],
        [ 0.39828798,  1.1067727 ,  0.09794924, -0.82035196],
        [ 0.6827874 ,  0.9431764 ,  0.73458517, -0.25488228]]],
      dtype=float32)>

### 填充和步幅

池化层也可以设置填充和步幅，这里使用keras中的pool层

In [18]:
with tf.device("/cpu:0"):
    pool = tf.keras.layers.MaxPooling2D(pool_size=(3,3),strides=3,padding="SAME")
    x = tf.random.normal(shape=(1,5,5,3))
    out = pool(x)

In [19]:
out

<tf.Tensor: id=239, shape=(1, 2, 2, 3), dtype=float32, numpy=
array([[[[1.5895929 , 1.1780937 , 2.143267  ],
         [0.9174139 , 2.610871  , 1.6962621 ]],

        [[0.04699831, 0.59916496, 1.2139673 ],
         [1.0487039 , 0.35977775, 1.7876493 ]]]], dtype=float32)>

In [20]:
with tf.device("/cpu:0"):
    pool = tf.keras.layers.AveragePooling2D(pool_size=(3,3),strides=3,padding="SAME")
    x = tf.random.normal(shape=(1,5,5,3))
    out = pool(x)

In [21]:
out

<tf.Tensor: id=246, shape=(1, 2, 2, 3), dtype=float32, numpy=
array([[[[ 0.34536174,  0.3740858 ,  0.12317541],
         [-0.00785424,  0.42756078, -0.72562927]],

        [[ 0.27400064, -0.15436958,  0.63357   ],
         [ 0.11758621,  0.092325  , -0.13735373]]]], dtype=float32)>