In [1]:
import tensorflow as tf
import tensorflow.keras as keras
import random
tf.__version__

'2.0.0-rc1'

### 生成数据

In [2]:
true_w = [2.4,4]
true_b = -3.4
num_inputs = 2
num_examples = 1000

features = tf.random.normal(shape=[num_examples,num_inputs])

In [3]:
lables =tf.reduce_sum( tf.constant(true_w) * features,axis=1)  + tf.constant(true_b)

In [4]:
lables += tf.random.normal(shape=lables.shape,stddev=0.01)

In [5]:
features[:5],lables[:5]

(<tf.Tensor: id=22, shape=(5, 2), dtype=float32, numpy=
 array([[-1.46353   ,  0.80882746],
        [ 0.60497916, -0.5954714 ],
        [ 1.5794803 , -0.3835507 ],
        [-0.02605676,  0.37747917],
        [-2.3835993 ,  0.7381624 ]], dtype=float32)>,
 <tf.Tensor: id=26, shape=(5,), dtype=float32, numpy=
 array([-3.6829205, -4.3448334, -1.1401888, -1.9556425, -6.158499 ],
       dtype=float32)>)

### 创建模型

In [12]:
model = keras.Sequential()
model.add(keras.layers.Dense(1))

In [13]:
model.compile(loss = "mse",optimizer=keras.optimizers.SGD(learning_rate=0.03))

In [14]:
steps_per_epoch = num_examples // batch_size
model.fit(x=features,y=lables,epochs=10,batch_size=batch_size)


# model.fit(dataset,epochs=10,steps_per_epoch=steps_per_epoch)

Train on 1000 samples
Epoch 1/10
1000/1000 [==============================] - 0s 475us/sample - loss: 8.2360
Epoch 2/10
1000/1000 [==============================] - 0s 62us/sample - loss: 0.1906
Epoch 3/10
1000/1000 [==============================] - 0s 65us/sample - loss: 0.0045
Epoch 4/10
1000/1000 [==============================] - 0s 78us/sample - loss: 2.0227e-04
Epoch 5/10
1000/1000 [==============================] - 0s 58us/sample - loss: 1.0110e-04
Epoch 6/10
1000/1000 [==============================] - 0s 58us/sample - loss: 9.8423e-05
Epoch 7/10
1000/1000 [==============================] - 0s 59us/sample - loss: 9.8733e-05
Epoch 8/10
1000/1000 [==============================] - 0s 57us/sample - loss: 9.8430e-05
Epoch 9/10
1000/1000 [==============================] - 0s 61us/sample - loss: 9.8538e-05
Epoch 10/10
1000/1000 [==============================] - 0s 57us/sample - loss: 9.8630e-05


In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              multiple                  3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.weights

[<tf.Variable 'sequential_1/dense_1/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[2.3999934],
        [3.9996881]], dtype=float32)>,
 <tf.Variable 'sequential_1/dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([-3.4001477], dtype=float32)>]