In [1]:
import tensorflow as tf
tf.__version__

'2.0.0-rc1'

### 生成数据

构造 y = 2.4x1 + 4x2 -3.4

In [2]:
true_w = [2.4,4]
true_b = -3.4
num_inputs = 2
num_examples = 1000

features = tf.random.normal(shape=[num_examples,num_inputs])

In [3]:
features[:5]

<tf.Tensor: id=9, shape=(5, 2), dtype=float32, numpy=
array([[ 1.8879708 , -2.1336825 ],
       [ 0.7376135 ,  0.5931834 ],
       [-0.0588356 ,  0.10758081],
       [-0.9199985 ,  0.55885845],
       [ 1.6018661 , -0.19825228]], dtype=float32)>

In [15]:
lables =tf.reduce_sum( tf.constant(true_w) * features,axis=1)  + tf.constant(true_b)
lables[:5]

<tf.Tensor: id=81, shape=(5,), dtype=float32, numpy=
array([-7.4035997,  0.7430062, -3.1108823, -3.372563 , -0.3485303],
      dtype=float32)>

In [16]:
lables += tf.random.normal(shape=lables.shape,stddev=0.01)
lables[:5]

<tf.Tensor: id=92, shape=(5,), dtype=float32, numpy=
array([-7.405033  ,  0.73529685, -3.113644  , -3.376704  , -0.35880834],
      dtype=float32)>

In [17]:
features[0],lables[0]

(<tf.Tensor: id=96, shape=(2,), dtype=float32, numpy=array([ 1.8879708, -2.1336825], dtype=float32)>,
 <tf.Tensor: id=100, shape=(), dtype=float32, numpy=-7.405033>)

In [18]:
import random

In [19]:
def data_inter(batch_size,features,lanbles):
    num = len(features)
    indices = list(range(num))
    random.shuffle(indices)
    
    for i in range(0,num,batch_size):
        j = min(i+batch_size,num)
        yield features[i:j],lanbles[i:j]

In [20]:
batch_size = 32

In [21]:
inter = data_inter(batch_size,features,lables)

In [23]:
for x,y in inter:
    print(x,y)
    break

tf.Tensor(
[[ 1.8879708  -2.1336825 ]
 [ 0.7376135   0.5931834 ]
 [-0.0588356   0.10758081]
 [-0.9199985   0.55885845]
 [ 1.6018661  -0.19825228]
 [ 1.4773483   0.12092438]
 [-0.41717276  0.7841685 ]
 [ 1.2573222  -1.9573232 ]
 [-0.57944393  0.73416156]
 [-0.7457675  -0.5676988 ]
 [ 2.1712627   0.6329351 ]
 [ 0.48991936 -1.4965094 ]
 [ 0.7654578   0.50515807]
 [-1.6901743  -0.3470743 ]
 [ 0.4395262  -1.9570932 ]
 [-0.1203185   1.9836766 ]
 [ 1.9470811  -0.63036686]
 [-0.6167048  -1.1750531 ]
 [ 1.0256116  -0.15167119]
 [ 0.06153234 -1.1670824 ]
 [-1.0446807  -0.82333976]
 [-0.20178725 -0.38839832]
 [ 0.28102392 -0.09577035]
 [ 1.4649645   0.53739774]
 [-0.3270892  -2.1727982 ]
 [ 0.10991778 -0.48117778]
 [ 0.6049704  -0.44234428]
 [ 0.9442001  -1.8626257 ]
 [ 0.31373918  0.92262375]
 [ 0.83188957 -0.90864545]
 [-0.6465388  -1.1066452 ]
 [ 1.099742    0.96116716]], shape=(32, 2), dtype=float32) tf.Tensor(
[ -7.405033     0.73529685  -3.113644    -3.376704    -0.35880834
   0.6283699   -

### 参数初始化

In [43]:
w = tf.random.normal(shape=[2,1])
b = tf.ones(shape=[1,])

### 定义模型

In [26]:
def linreg(x,w,b):
    return tf.matmul(x,w) + b

In [29]:
for x,y in inter:
    print(linreg(x,w,b))
    break

tf.Tensor(
[[ 1.1701056 ]
 [ 0.98041487]
 [ 2.7241085 ]
 [ 1.2453179 ]
 [ 1.539138  ]
 [ 0.38368398]
 [ 2.4891243 ]
 [ 2.6493478 ]
 [-0.5020764 ]
 [ 2.4497252 ]
 [ 0.9295529 ]
 [ 2.3989272 ]
 [ 0.5751362 ]
 [ 2.481438  ]
 [ 0.7485478 ]
 [ 1.3430793 ]
 [ 2.3306067 ]
 [ 4.075533  ]
 [ 1.1074067 ]
 [ 1.1886427 ]
 [ 1.3905013 ]
 [ 1.7931782 ]
 [-0.18970537]
 [-0.2932613 ]
 [ 2.194859  ]
 [ 3.1251433 ]
 [ 2.121282  ]
 [ 0.8538486 ]
 [-1.4193251 ]
 [ 1.3592868 ]
 [ 1.2681595 ]
 [-0.1793561 ]], shape=(32, 1), dtype=float32)


### 定义损失

In [34]:
def square_error(y_true,y):
    return (tf.reshape(y_true,y.shape)-y)**2 /2

In [35]:
for x,y in inter:
    print(square_error(y,linreg(x,w,b)))
    break

tf.Tensor(
[[2.2089062e+01]
 [4.4624802e+01]
 [5.6095438e+00]
 [1.9613155e+01]
 [3.4240967e+01]
 [1.2041559e+00]
 [3.9677455e+00]
 [6.3409529e+00]
 [5.8076504e+01]
 [7.5864644e+00]
 [4.5043025e+00]
 [6.1246214e+00]
 [5.0740444e+01]
 [2.0532818e+01]
 [6.5272129e-01]
 [3.8319037e+00]
 [1.7396671e+01]
 [2.3417831e+01]
 [6.7764487e+00]
 [6.6569722e-03]
 [2.6211664e+01]
 [1.2910376e+01]
 [1.3601874e+00]
 [2.1165758e+01]
 [1.4009410e+02]
 [5.0590414e-01]
 [1.4200706e+00]
 [1.6633406e+01]
 [1.8196001e+01]
 [1.4663843e+02]
 [3.0048108e+00]
 [1.8061469e-01]], shape=(32, 1), dtype=float32)


### 定义优化算法

In [37]:
# def sgd(params , lr,batch_size):
#     for param in params:
#         param[:] = param -lr * param.grad /batch_size

### 训练

In [45]:
lr = 0.03
epchos = 10

for i in range(epchos):
    for X,y in data_inter(batch_size,features,lables):
        with tf.GradientTape() as tape:
            tape.watch(w)
            tape.watch(b)
            y_hat = linreg(X,w,b)
            loss = square_error(y,y_hat)
        dw,db = tape.gradient(loss,[w,b])
        w = w - lr * dw /batch_size
        b = b - lr *db /batch_size
    
    epcho_loss = square_error(y,linreg(X,w,b))
    print("epcho:",i+1,"loss:",tf.reduce_sum(epcho_loss).numpy())

epcho: 1 loss: 39.338524
epcho: 2 loss: 6.263608
epcho: 3 loss: 0.9988285
epcho: 4 loss: 0.15962106
epcho: 5 loss: 0.02571959
epcho: 6 loss: 0.004364623
epcho: 7 loss: 0.0009760137
epcho: 8 loss: 0.00044880147
epcho: 9 loss: 0.00037217562
epcho: 10 loss: 0.00036362233


In [46]:
w,b

(<tf.Tensor: id=56227, shape=(2, 1), dtype=float32, numpy=
 array([[2.3992229],
        [3.9997842]], dtype=float32)>,
 <tf.Tensor: id=56232, shape=(1,), dtype=float32, numpy=array([-3.3997357], dtype=float32)>)